### ISSUE TITLE
organizing react section

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#110]
lets put it into a separate document for now

https://github.com/LLazyEmail/react-email-table/issues/331

https://github.com/LLazyEmail/react-email-table/issues/329

https://github.com/LLazyEmail/react-email-table/issues/327

https://github.com/LLazyEmail/react-email-table/issues/326

https://github.com/LLazyEmail/react-email-table/issues/174

https://github.com/LLazyEmail/react-email-table/issues/135

https://github.com/LLazyEmail/react-email-table/issues/85

https://github.com/LLazyEmail/react-email-table/issues/22

https://github.com/LLazyEmail/react-email-table/issues/20

https://github.com/LLazyEmail/react-email-table/issues/19

**Comment by Svitlana007** [comment]
Done
[Create React section.md #118](https://github.com/LLazyEmail/documentation/pull/118)
