### ISSUE TITLE
add links to all published links related to react into these readme files

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#111]
- https://llazyemail.github.io/documentation/docs/React-Design-System
- https://llazyemail.github.io/documentation/docs/React-Design-System/React-section
- https://llazyemail.github.io/documentation/docs/React-Design-System/react-tasks

**Repositories**

- https://github.com/LLazyEmail/react-email-typography-components
- https://github.com/LLazyEmail/nextjs-preview
- https://github.com/LLazyEmail/react-email-miscellaneous-components
- https://github.com/LLazyEmail/react-sendgrid-form
- https://github.com/LLazyEmail/react-email-template
- https://github.com/LLazyEmail/react-email-table
- https://github.com/LLazyEmail/email-template-react
- https://github.com/LLazyEmail/react-email-letter-components

- https://github.com/LLazyEmail/remix-hn-react-email-template
- https://github.com/LLazyEmail/remix-venmo-react-email-template
- https://github.com/LLazyEmail/remix-taskrabbit-react-email-template
- https://github.com/LLazyEmail/remix-uber-react-email-template
- https://github.com/LLazyEmail/remix-ecommerce-react-email-template
- https://github.com/LLazyEmail/remix-google-billing-email-template
- https://github.com/LLazyEmail/remix-amazon-billing-email-template
- https://github.com/LLazyEmail/remix-stripe-billing-email-template

**Comment by Svitlana007** [comment]
> * https://llazyemail.github.io/documentation/docs/React-Design-System/react

![image](https://user-images.githubusercontent.com/109110458/185807937-9dfbc890-fac9-4d72-a2dc-a47730e4bc01.png)

**Comment by Svitlana007** [comment]
@atherdon  можете детальніше розяснити, що потрібно зробити

**Comment by atherdon** [comment]
зараз подивлюся. та добавлю 3й лiнк

**Comment by atherdon** [comment]
https://user-images.githubusercontent.com/1469198/185808923-55393efc-8cbd-4695-ae53-47a1ed0183b5.mp4

**Comment by Svitlana007** [comment]
Done
