### ISSUE TITLE
create "devops" folder

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#134]
place: `/docs/`

to move files into it:
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/DevOps.md
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/ivan.md
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/pipeline.md

**Comment by Svitlana007** [comment]
Done
