### ISSUE TITLE
missing names in sidebar @ few pages

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#136]
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/ivan.md
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/mdx-exploration.md
- https://github.com/LLazyEmail/documentation/edit/main/docs/generator/test/LLazyEmail%20Documentation.md (please also remove `%20` sign from the filename)
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/todo.md (can you put `markdown-to-email repository simple tags with todo attribute` as title)
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/display-factory-73.md
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/organized-tasks.md
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/entities.md
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/improvements.md
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/improvements-entities.md

for those files let's add settings section in the begining of each files

similar to this one, but fill with different settings(pick what do you think is better, we'll change it later, maybe)
```
---
id: react-table-module
title: react-table-module-tasks
sidebar_label: react-table-repository
---
```

**Comment by atherdon** [comment]
after this task @atherdon need to update this line: https://github.com/LLazyEmail/documentation/blob/main/docusaurus.config.js#L56

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/documentation/edit/main/docs/generator/test/LLazyEmail%20Documentation.md (please also remove `%20` sign from the filename)

хтось вже це зробив

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/todo.md (can you put `markdown-to-email repository simple tags with todo attribute` as title)

[PR](https://github.com/LLazyEmail/documentation/pull/156)

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/ivan.md

файл не існує
![image](https://user-images.githubusercontent.com/109110458/188225774-6b916545-8848-4e59-95fd-718f5a901c59.png)

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/mdx-exploration.md

[PR](https://github.com/LLazyEmail/documentation/pull/157)


> * https://github.com/LLazyEmail/documentation/edit/main/docs/generator/test/LLazyEmail%20Documentation.md (please also remove `%20` sign from the filename)

[PR](https://github.com/LLazyEmail/documentation/pull/158)


> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/todo.md (can you put `markdown-to-email repository simple tags with todo attribute` as title)

[PR](https://github.com/LLazyEmail/documentation/pull/159)


> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/display-factory-73.md

[PR](https://github.com/LLazyEmail/documentation/pull/160)


> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/organized-tasks.md

[PR](https://github.com/LLazyEmail/documentation/pull/161)


> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/entities.md

![image](https://user-images.githubusercontent.com/109110458/188227508-ff93d344-201a-4904-8945-775838e2d8a3.png)


> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/improvements.md

![image](https://user-images.githubusercontent.com/109110458/188227583-fc145776-ccba-4723-b7d6-3f0e5289b4dc.png)


> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/improvements-entities.md

![image](https://user-images.githubusercontent.com/109110458/188227643-58b4d73c-426f-4c19-99d7-0084dee2cc14.png)

**Comment by atherdon** [comment]
> > * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/ivan.md
> 
> файл не існує ![image](https://user-images.githubusercontent.com/109110458/188225774-6b916545-8848-4e59-95fd-718f5a901c59.png)

Ми перенесли його у девопс якщо я не помиляюся

**Comment by Svitlana007** [comment]
> ---
> id: react-table-module
> title: react-table-module-tasks
> sidebar_label: react-table-repository
> ---

yep
[PR](https://github.com/LLazyEmail/documentation/pull/164)

**Comment by Svitlana007** [comment]
> > * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/entities.md
> 
> ![image](https://user-images.githubusercontent.com/109110458/188227508-ff93d344-201a-4904-8945-775838e2d8a3.png)

[PR](https://github.com/LLazyEmail/documentation/pull/165)

**Comment by Svitlana007** [comment]
> > * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/improvements-entities.md
> 
> ![image](https://user-images.githubusercontent.com/109110458/188227643-58b4d73c-426f-4c19-99d7-0084dee2cc14.png)

[PR](https://github.com/LLazyEmail/documentation/pull/166)

**Comment by Svitlana007** [comment]
> > * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements/improvements.md
> 
> ![image](https://user-images.githubusercontent.com/109110458/188227583-fc145776-ccba-4723-b7d6-3f0e5289b4dc.png)

[PR](https://github.com/LLazyEmail/documentation/pull/167)

**Comment by Svitlana007** [comment]
Find`s all documents

**Comment by atherdon** [comment]
Closing it then, but we still need to fix a pr for todo file

**Comment by Svitlana007** [comment]
> Closing it then, but we still need to fix a pr for todo file

зараз наче ок, перевіряйте!

**Comment by atherdon** [comment]
Все ще бачу конфликт тут
https://github.com/LLazyEmail/documentation/pull/159
