### ISSUE TITLE
hard to read todo page

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#137]
**problem**: with our current formatting it's hard to read/navigate inside of this page via documentation website.

it's because we have a lot "headings" ( with `##` or `###`) tags. 

![image](https://user-images.githubusercontent.com/1469198/187546233-2b01ba1a-217e-4a69-b2b6-69c1ea63f66d.png)

link: https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/todo.md

**simple solution**: to add one more symbol to each heading. 
so sub-heading inside each task will be "down-graded": heading with `##` will become `###` and `###` will become `####`, but please pay attention to hierarchy of them - there a few sub-sections inside, like **Other design tenets**

I upgraded task1 section, so you can start with tasks that are going after it.

below is fixed version, from Task 1

![image](https://user-images.githubusercontent.com/1469198/187546740-e3ea3193-3843-48a7-9120-9cfda7553064.png)

---

**Comment by Svitlana007** [comment]
Done
