### ISSUE TITLE
do we need to have this file in our docs section?

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#138]
file: https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/Collections%20of%20articles.md

i think we have a blog post already: https://llazyemail.github.io/documentation/blog/transactional-emails

if no, please delete it

**Comment by Svitlana007** [comment]
> if no, please delete it

ви мали на увазі, якщо є публікація в блозі, то видалити, вірно?

**Comment by atherdon** [comment]
Мабуть так

**Comment by Svitlana007** [comment]
[Delete Collections of articles.md #142](https://github.com/LLazyEmail/documentation/pull/142)
