### ISSUE TITLE
images are broken

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#139]
https://llazyemail.github.io/documentation/docs/generator/test/errors
![image](https://user-images.githubusercontent.com/1469198/187552182-9af8da33-1e23-408b-ac0a-8a2815ce9644.png)

can you take a look into that file, maybe it's easy to fix?

if no - i'll take a deeper look

**Comment by Svitlana007** [comment]
@atherdon Чомусь ця задача впала мені на пошту в розділ "Оновлення" і я її не побачила, сорі, дивлюсь

**Comment by Svitlana007** [comment]
[PR](https://github.com/LLazyEmail/documentation/pull/171)

**Comment by atherdon** [comment]
картинки все еще ломаются в 5м таске

**Comment by Svitlana007** [comment]
> картинки все еще ломаются в 5м таске

[PR](https://github.com/LLazyEmail/documentation/pull/179) а після цього? @atherdon

**Comment by atherdon** [comment]
хочу щоб ви подивились ))

**Comment by Svitlana007** [comment]
> хочу щоб ви подивились ))

Не працює...

**Comment by Svitlana007** [comment]
@atherdon [PR](https://github.com/LLazyEmail/documentation/pull/185) тепер має працювати)

**Comment by atherdon** [comment]
дякую
