### ISSUE TITLE
latest reogranization fixes

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#168]
ми перенесли 2 папки з папки test.
наче все добре, але докузаурусу щось не подобаеться.

можете подивитися на сайтi та мабуть виправити, бо кажется що щось ломаеться( я про ссилки у sidebar )
![image](https://user-images.githubusercontent.com/1469198/188476863-aae68280-9c41-473e-be64-e05914544e2d.png)

посилання impovements: https://llazyemail.github.io/documentation/docs/improvements

посилання devops: https://llazyemail.github.io/documentation/docs/devops

reference link: https://github.com/LLazyEmail/documentation/issues/136#issue-1356318207

**Comment by Svitlana007** [comment]
Створила [PR](https://github.com/LLazyEmail/documentation/pull/169), хоча не до кінця розумію, що має бути в цьому sidebar, але вже знаю звідки цей набір слів)

**Comment by atherdon** [comment]
looks better now, but we have another thing to update

![image](https://user-images.githubusercontent.com/1469198/189633056-0221076f-1b24-4652-8b10-8df6b95bf3a9.png)


I think we can fix it as well
link: https://llazyemail.github.io/documentation/docs/improvements/entitie

**Comment by Svitlana007** [comment]
> I think we can fix it as well

[PR](https://github.com/LLazyEmail/documentation/pull/173)

**Comment by atherdon** [comment]
у меня почему то пропали нотификации о новых пулл-реквестах. хорошо что вы делаете ссылку на PR в таске. еще можно делать меншн (`@atherdon`) меня в пулле - тогда наверное письмо на почту прийдет

сейчас посмотрю пулл

**Comment by atherdon** [comment]
все гуд, закриваю задачу
