### ISSUE TITLE
Done [PR](https://github.com/LLazyEmail/documentation/pull/182)

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#183]
Done [PR](https://github.com/LLazyEmail/documentation/pull/182)

p.s. не додала посилання на репозиторій до 3 і 4 пунктів, бо не знала до яких це репозиторій відноситься

_Originally posted by @Svitlana007 in https://github.com/LLazyEmail/documentation/issues/177#issuecomment-1250240418_

**Comment by atherdon** [comment]
@Svitlana007 там той самий репозiторiй - markdown to email. робим зараз таке посилання, а потiм добавимо детальний опис

**Comment by Svitlana007** [comment]
Done [PR](https://github.com/LLazyEmail/documentation/pull/184)

**Comment by atherdon** [comment]
дякую
