### ISSUE TITLE
move this file into our repository please

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#19]
https://github.com/albinotonnina/feature-proposal-template/blob/master/.github/ISSUE_TEMPLATE/feature-proposal.md

**Comment by atherdon** [comment]
https://user-images.githubusercontent.com/1469198/182621706-107ee09e-5ea7-452a-a21b-6edcb9227474.mp4

**Comment by Svitlana007** [comment]
Мені потрібно до кожної задачі додати "тіло" з даного документу (https://github.com/albinotonnina/feature-proposal-template/blob/master/.github/ISSUE_TEMPLATE/feature-proposal.md)?

**Comment by atherdon** [comment]
так

**Comment by atherdon** [comment]
ми також можемо перенести шаблон у цю задачу - https://github.com/LLazyEmail/markdown-to-email/issues/1446

**Comment by Svitlana007** [comment]
> ми також можемо перенести шаблон у цю задачу - [LLazyEmail/markdown-to-email#1446](https://github.com/LLazyEmail/markdown-to-email/issues/1446)

Done

**Comment by Svitlana007** [comment]
> Мені потрібно до кожної задачі додати "тіло" з даного документу (https://github.com/albinotonnina/feature-proposal-template/blob/master/.github/ISSUE_TEMPLATE/feature-proposal.md)?

@atherdon для старту обрала файл react.md, якщо все ок, то опрацюю наступні по аналогії.
Чомусь по шаблону:

name: Feature proposal
about: Suggest an idea for this project
title: ""
labels: ""
assignees: ""

табличка не получалась, тому використала наступний шаблон для таблиці:

| Ім'я           | Прізвище    | Розробка        |
|:-------------- |:-----------:| ---------------:|
| за лівим краєм | по центру   | за правим краєм |
| Лінус          | Торвальдс   | Linux           |
| Денніс         | Рітчі       | С               |
| Джек           | Дорсі       | Twitter         |

**Comment by atherdon** [comment]
зараз мабуть таблиця нам не дуже потрiбна, тому шо в нас мало народу працюэ ))) тому всi tasks будуть для Вадима. але можемо лишити зараз. менi треба подивитися взагалi та подумати - треба нам це чи не

**Comment by atherdon** [comment]
можете продовжувати

**Comment by atherdon** [comment]
we can add a feature proposal template into 

- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements.md
- https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/todo.md

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/todo.md

Done

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements.md

Done

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements-entities.md

тут не бачу задач...

**Comment by atherdon** [comment]
> > * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements-entities.md
> 
> тут не бачу задач...

це одна велика задача. робив 2 днi. на цей час - треба просто добавити секцii iз proposal template.
я сам спробую поредагувати потiм

**Comment by Svitlana007** [comment]
> > > * https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements-entities.md
> > 
> > 
> > тут не бачу задач...
> 
> це одна велика задача. робив 2 днi. на цей час - треба просто добавити секцii iз proposal template. я сам спробую поредагувати потiм

done
