### ISSUE TITLE
update settings

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#67]
replace blog post settings with

```
url: https://github.com/atherdon
  image_url: https://github.com/atherdon.png
```

**Comment by Svitlana007** [comment]
@atherdon це точно мені задача?)

**Comment by atherdon** [comment]
Так 

https://user-images.githubusercontent.com/1469198/184476601-d88e335d-bcc0-44d6-9ace-aee1153db074.mp4

**Comment by Svitlana007** [comment]
@atherdon все зрозуміло, дякую за роз'яснення!

**Comment by Svitlana007** [comment]
> url: https://github.com/atherdon
>   image_url: https://github.com/atherdon.png

Done

**Comment by atherdon** [comment]
вам дякую
