### ISSUE TITLE
move to mdx page

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#69]
from: https://github.com/LLazyEmail/content-marketing/blob/main/a.md
to: https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/mdx-exploration.md

**Comment by Svitlana007** [comment]
Done 

[Update mdx-exploration.md #73](https://github.com/LLazyEmail/documentation/pull/73)

[Delete a.md #5](https://github.com/LLazyEmail/content-marketing/pull/5) from [content-marketing](https://github.com/LLazyEmail/content-marketing)
