### ISSUE TITLE
move to documentation

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#70]
https://github.com/LLazyEmail/content-marketing/blob/main/ivan.md

each `###` is a separate task, you can wrap them as Task# x

**Comment by Svitlana007** [comment]
Done

[Create ivan.md #74](https://github.com/LLazyEmail/documentation/pull/74) in `LLazyEmail/documentation`

[Delete ivan.md #6](https://github.com/LLazyEmail/content-marketing/pull/6) in `LLazyEmail/content-marketing`
