### ISSUE TITLE
move templates into static/templates 

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/documentation#92]
- vouchful: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/05%20Vouchful/01-weekly-digest/index.html
- amazon billing: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/09%20Billing/amazon.html
- google billing: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/09%20Billing/google.html
- stripe billing: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/09%20Billing/stripe.html
- uber: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/02%20Startups/uber/index.html
- taskrabbit: https://github.com/LLazyEmail/free-email-templates-to-try/tree/main/02%20Startups/welcome-to-taskrabbit2/src
- venmo: https://github.com/LLazyEmail/free-email-templates-to-try/tree/main/02%20Startups/big-news-for-small-business-venmo-business-profiles-are-here/src

**Comment by Svitlana007** [comment]
> * vouchful: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/05%20Vouchful/01-weekly-digest/index.html

[Create index.html #93](https://github.com/LLazyEmail/documentation/pull/93)
[Delete index.html #2](https://github.com/LLazyEmail/free-email-templates-to-try/pull/2)

**Comment by Svitlana007** [comment]
> * amazon billing: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/09%20Billing/amazon.html

[Create amazon.html #94](https://github.com/LLazyEmail/documentation/pull/94)
[Delete amazon.html #3](https://github.com/LLazyEmail/free-email-templates-to-try/pull/3)



> * google billing: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/09%20Billing/google.html

[Create google.html #95](https://github.com/LLazyEmail/documentation/pull/95)
[Delete google.html #4](https://github.com/LLazyEmail/free-email-templates-to-try/pull/4)

**Comment by Svitlana007** [comment]
> * stripe billing: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/09%20Billing/stripe.html

[Create stripe.html #96](https://github.com/LLazyEmail/documentation/pull/96)
[Delete stripe.html #5](https://github.com/LLazyEmail/free-email-templates-to-try/pull/5)


> * uber: https://github.com/LLazyEmail/free-email-templates-to-try/blob/main/02%20Startups/uber/index.html

[Create uber index.html #97](https://github.com/LLazyEmail/documentation/pull/97)
[Delete index.html #6](https://github.com/LLazyEmail/free-email-templates-to-try/pull/6)


> * taskrabbit: https://github.com/LLazyEmail/free-email-templates-to-try/tree/main/02%20Startups/welcome-to-taskrabbit2/src

[Create taskrabbit index.html #98](https://github.com/LLazyEmail/documentation/pull/98)
[Delete index.html #7](https://github.com/LLazyEmail/free-email-templates-to-try/pull/7)


> * venmo: https://github.com/LLazyEmail/free-email-templates-to-try/tree/main/02%20Startups/big-news-for-small-business-venmo-business-profiles-are-here/src

[Create venmo index.html #99](https://github.com/LLazyEmail/documentation/pull/99)
[Delete index.html #8](https://github.com/LLazyEmail/free-email-templates-to-try/pull/8)

**Comment by atherdon** [comment]
can you also move template files from this folder too: https://github.com/LLazyEmail/documentation/tree/main/docs/templates

**Comment by Svitlana007** [comment]
> can you also move template files from this folder too

Done

**Comment by atherdon** [comment]
thanks!

**Comment by atherdon** [comment]
not sure if we moved all templates, i see other 3 HTML files in this folder https://github.com/LLazyEmail/documentation/tree/main/docs/templates

**Comment by Svitlana007** [comment]
> not sure if we moved all templates, i see other 3 HTML files in this folder https://github.com/LLazyEmail/documentation/tree/main/docs/templates

Done

**Comment by atherdon** [comment]
thanks!

**Comment by atherdon** [comment]
can you also delete the whole folder, please
 https://github.com/LLazyEmail/documentation/tree/main/docs/templates
I think we don't need it any more

**Comment by Svitlana007** [comment]
> can you also delete the whole folder, please
> https://github.com/LLazyEmail/documentation/tree/main/docs/templates
> I think we don't need it any more

я не можу це зробити(
![image](https://user-images.githubusercontent.com/109110458/185764741-7c5a45de-b933-421a-bd31-3a3739c8fb27.png)

**Comment by atherdon** [comment]
добре, зроблю це сам.

**Comment by Svitlana007** [comment]
> добре, зроблю це сам.

ніби получилось)

**Comment by atherdon** [comment]
так, approved - гiтхаб дурний вже декiлька мiсяцiв
